import MenuLateral from './Components/menu-lateral/MenuLateral';
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Prato Faminto',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <MenuLateral>
      <body className="h-screen w-screen flex items-center bg-gray-200 justify-center">
        {children}
      </body>
    </MenuLateral>
    
  );
}
